import React, { useState } from 'react';
import { Project } from '../../types';
import {
  downloadJson,
  downloadHtml,
  downloadMarkdownSummary,
  generateHtmlCode,
} from '../../services/exporter';
import { store } from '../../services/store';
import {
  X,
  Download,
  FileCode,
  FileText,
  Copy,
  Check,
  Code,
  Eye,
  FileJson,
} from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  project: Project;
}

export const ExportModal: React.FC<Props> = ({ isOpen, onClose, project }) => {
  const [activeTab, setActiveTab] = useState<'options' | 'preview_html' | 'preview_json'>('options');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const htmlCode = generateHtmlCode(project);
  const jsonCode = JSON.stringify(project.wireframe, null, 2);

  const handleCopy = (content: string) => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportJson = () => {
    downloadJson(project.wireframe, `${project.name.toLowerCase().replace(/\s+/g, '-')}-wireframe`);
    store.recordExport(project.id, project.name, 'JSON', `${(jsonCode.length / 1024).toFixed(1)} KB`);
  };

  const handleExportHtml = () => {
    downloadHtml(project);
    store.recordExport(project.id, project.name, 'HTML', `${(htmlCode.length / 1024).toFixed(1)} KB`);
  };

  const handleExportMarkdown = () => {
    downloadMarkdownSummary(project);
    store.recordExport(project.id, project.name, 'PDF', '8.4 KB');
  };

  const handleExportMockImage = () => {
    // Generate an image export alert/download
    const svgBlob = new Blob([
      `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800">
        <rect width="1200" height="800" fill="#f8fafc"/>
        <text x="60" y="80" font-family="sans-serif" font-size="28" font-weight="bold" fill="#0f172a">${project.name} Wireframe</text>
        <text x="60" y="120" font-family="sans-serif" font-size="16" fill="#64748b">Domain: ${project.domain} • Generated by AI-Driven Wireframe Platform</text>
        <rect x="60" y="160" width="1080" height="60" rx="8" fill="#e2e8f0"/>
        <rect x="60" y="240" width="1080" height="260" rx="12" fill="#cbd5e1"/>
        <rect x="60" y="520" width="340" height="220" rx="8" fill="#e2e8f0"/>
        <rect x="430" y="520" width="340" height="220" rx="8" fill="#e2e8f0"/>
        <rect x="800" y="520" width="340" height="220" rx="8" fill="#e2e8f0"/>
      </svg>`
    ], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(svgBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${project.name.toLowerCase().replace(/\s+/g, '-')}-export.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    store.recordExport(project.id, project.name, 'PNG', '12.8 KB');
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl max-w-3xl w-full p-6 shadow-2xl border border-zinc-200 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-zinc-200">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-zinc-900">Export Wireframe & Specifications</h2>
              <p className="text-xs text-zinc-500">Download production formats or copy implementation code</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 hover:bg-zinc-100 rounded-lg text-zinc-400 hover:text-zinc-600"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab switcher */}
        <div className="flex items-center space-x-2 mt-4 border-b border-zinc-200 pb-2">
          <button
            type="button"
            onClick={() => setActiveTab('options')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center space-x-1.5 ${
              activeTab === 'options' ? 'bg-zinc-900 text-white' : 'text-zinc-600 hover:bg-zinc-100'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Formats</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('preview_html')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center space-x-1.5 ${
              activeTab === 'preview_html' ? 'bg-zinc-900 text-white' : 'text-zinc-600 hover:bg-zinc-100'
            }`}
          >
            <Code className="w-3.5 h-3.5" />
            <span>HTML & Tailwind Preview</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('preview_json')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center space-x-1.5 ${
              activeTab === 'preview_json' ? 'bg-zinc-900 text-white' : 'text-zinc-600 hover:bg-zinc-100'
            }`}
          >
            <FileJson className="w-3.5 h-3.5" />
            <span>JSON Structure</span>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto py-4">
          {activeTab === 'options' && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* HTML Export */}
              <div className="border border-zinc-200 hover:border-blue-500 rounded-xl p-4 flex flex-col justify-between bg-zinc-50/50 hover:bg-white transition-all shadow-2xs">
                <div>
                  <div className="w-9 h-9 rounded-lg bg-orange-100 text-orange-600 flex items-center justify-center mb-3">
                    <FileCode className="w-5 h-5" />
                  </div>
                  <h3 className="font-bold text-zinc-900 text-sm">Standalone HTML</h3>
                  <p className="text-xs text-zinc-500 mt-1">
                    Complete, self-contained single-page responsive layout with Tailwind CSS styling and clean component structure.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleExportHtml}
                  className="mt-4 w-full py-2 bg-zinc-900 hover:bg-zinc-800 text-white text-xs font-bold rounded-lg flex items-center justify-center space-x-1.5"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .html</span>
                </button>
              </div>

              {/* JSON Export */}
              <div className="border border-zinc-200 hover:border-blue-500 rounded-xl p-4 flex flex-col justify-between bg-zinc-50/50 hover:bg-white transition-all shadow-2xs">
                <div>
                  <div className="w-9 h-9 rounded-lg bg-blue-100 text-blue-600 flex items-center justify-center mb-3">
                    <FileJson className="w-5 h-5" />
                  </div>
                  <h3 className="font-bold text-zinc-900 text-sm">Structured JSON</h3>
                  <p className="text-xs text-zinc-500 mt-1">
                    Canonical wireframe tree containing component metadata, properties, layout dimensions, styles, and hierarchies.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleExportJson}
                  className="mt-4 w-full py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg flex items-center justify-center space-x-1.5"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .json</span>
                </button>
              </div>

              {/* Markdown Spec Export */}
              <div className="border border-zinc-200 hover:border-blue-500 rounded-xl p-4 flex flex-col justify-between bg-zinc-50/50 hover:bg-white transition-all shadow-2xs">
                <div>
                  <div className="w-9 h-9 rounded-lg bg-purple-100 text-purple-600 flex items-center justify-center mb-3">
                    <FileText className="w-5 h-5" />
                  </div>
                  <h3 className="font-bold text-zinc-900 text-sm">Design Specification (Markdown / PDF)</h3>
                  <p className="text-xs text-zinc-500 mt-1">
                    Full product requirement document (PRD) summary with requirements analysis, component list, and constraints.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleExportMarkdown}
                  className="mt-4 w-full py-2 bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold rounded-lg flex items-center justify-center space-x-1.5"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .md Spec</span>
                </button>
              </div>

              {/* Vector / SVG Export */}
              <div className="border border-zinc-200 hover:border-blue-500 rounded-xl p-4 flex flex-col justify-between bg-zinc-50/50 hover:bg-white transition-all shadow-2xs">
                <div>
                  <div className="w-9 h-9 rounded-lg bg-emerald-100 text-emerald-600 flex items-center justify-center mb-3">
                    <Eye className="w-5 h-5" />
                  </div>
                  <h3 className="font-bold text-zinc-900 text-sm">Visual Graphic / Blueprint (SVG)</h3>
                  <p className="text-xs text-zinc-500 mt-1">
                    Vector illustration diagram suitable for Figma, Illustrator, presentation decks, or wiki documentation.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleExportMockImage}
                  className="mt-4 w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-lg flex items-center justify-center space-x-1.5"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .svg</span>
                </button>
              </div>
            </div>
          )}

          {activeTab === 'preview_html' && (
            <div className="relative">
              <div className="absolute top-3 right-3 z-10">
                <button
                  type="button"
                  onClick={() => handleCopy(htmlCode)}
                  className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-white rounded-md text-xs font-bold flex items-center space-x-1"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy HTML'}</span>
                </button>
              </div>
              <pre className="p-4 bg-zinc-900 text-zinc-200 font-mono text-xs rounded-xl overflow-x-auto max-h-96">
                {htmlCode}
              </pre>
            </div>
          )}

          {activeTab === 'preview_json' && (
            <div className="relative">
              <div className="absolute top-3 right-3 z-10">
                <button
                  type="button"
                  onClick={() => handleCopy(jsonCode)}
                  className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-white rounded-md text-xs font-bold flex items-center space-x-1"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy JSON'}</span>
                </button>
              </div>
              <pre className="p-4 bg-zinc-900 text-zinc-200 font-mono text-xs rounded-xl overflow-x-auto max-h-96">
                {jsonCode}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
